
-- Expand Machine Learning Foundations book: add pages + exercises

-- Pattern Recognition (chapter 32a8dc6a...)
INSERT INTO public.pages (chapter_id, title, content, page_type, order_index) VALUES
('32a8dc6a-d56e-44e0-99ce-8fb4dadafafd', 'Features vs Labels', E'# Features vs Labels 🏷️\n\nMachines learn from two types of information: **features** and **labels**.\n\n## The Simple Idea\n\n```\n┌──────────────────────────────────────┐\n│         A HOUSE PRICE EXAMPLE         │\n│                                       │\n│   FEATURES (the inputs)               │\n│   • Size in square feet               │\n│   • Number of bedrooms                │\n│   • Neighborhood                      │\n│   • Year built                        │\n│            ↓                          │\n│   LABEL (the answer)                  │\n│   • Sale price = $450,000             │\n└──────────────────────────────────────┘\n```\n\n## Features\nFeatures are the **clues** the model uses. Think of them like ingredients in a recipe.\n\n## Labels\nLabels are the **correct answer** for each example. They are what we want the model to predict.\n\n## Real Example: Email Spam\n\n| Feature | Label |\n|---------|-------|\n| Subject has "WIN MONEY" | Spam |\n| Sender is your friend | Not spam |\n| Message has 50 links | Spam |\n\n> Good features = a smart model. Bad features = a confused model. Choosing features is half the job of a machine learning engineer.', 'concept', 4),
('32a8dc6a-d56e-44e0-99ce-8fb4dadafafd', 'How Models "See" Data', E'# How Models "See" Data 👀\n\nMachines do not see images, text, or sound the way we do. They see **numbers**.\n\n## Everything Becomes Numbers\n\n```\n┌──────────────────────────────────────┐\n│       TURNING DATA INTO NUMBERS       │\n│                                       │\n│   🖼️ Image → grid of pixel values     │\n│   📝 Text  → list of word codes       │\n│   🎵 Sound → wave measurements        │\n│   📊 Table → numbers and categories   │\n└──────────────────────────────────────┘\n```\n\n## Why This Matters\n\nMath only works on numbers. So before any learning happens, the data is converted.\n\n## Example: A Cat Photo\n\n```\nCat Photo (you see)         Model sees\n  🐱                        [[34, 56, 12],\n                             [78, 90, 11],\n                             [22, 45, 67]]\n```\n\nA tiny 3×3 grid of brightness numbers. Real photos have **millions** of these numbers.\n\n## Categories Also Become Numbers\n\n| Color | Code |\n|-------|------|\n| Red | 1 |\n| Blue | 2 |\n| Green | 3 |\n\n> This is why ML engineers spend so much time on **data preparation**. Clean numbers in = smart predictions out.', 'concept', 5);

-- Supervised Learning (chapter 27510ce5...)
INSERT INTO public.pages (chapter_id, title, content, page_type, order_index) VALUES
('27510ce5-12a7-4eb9-a5b8-2a5ecb864bae', 'Regression vs Classification', E'# Regression vs Classification 📊\n\nSupervised learning has two main flavors. Both learn from labeled examples, but they predict different things.\n\n## The Two Types\n\n```\n┌──────────────────────────────────────┐\n│         REGRESSION                    │\n│   Predicts a NUMBER                   │\n│                                       │\n│   Example: "$320,000"                 │\n│            "27°C"                     │\n│            "12 minutes"               │\n└──────────────────────────────────────┘\n\n┌──────────────────────────────────────┐\n│         CLASSIFICATION                │\n│   Predicts a CATEGORY                 │\n│                                       │\n│   Example: "Spam / Not spam"          │\n│            "Cat / Dog / Bird"         │\n│            "Approved / Denied"        │\n└──────────────────────────────────────┘\n```\n\n## Quick Comparison\n\n| Question | Type |\n|----------|------|\n| How much will this house sell for? | Regression |\n| Is this email spam? | Classification |\n| What will tomorrow''s temperature be? | Regression |\n| Is this tumor benign or malignant? | Classification |\n\n## Real Products\n\n- **Uber** uses regression to predict your ETA in minutes.\n- **Gmail** uses classification to sort spam from inbox.\n- **Netflix** uses both — regression for predicted ratings, classification for genre.\n\n> Pick the right type for your problem and you are already halfway to a working model.', 'concept', 3),
('27510ce5-12a7-4eb9-a5b8-2a5ecb864bae', 'Train and Test Split', E'# Train and Test Split ✂️\n\nA model that memorizes is not learning. To prove a model truly understands, we split our data into two parts.\n\n## The Split\n\n```\n┌──────────────────────────────────────┐\n│         YOUR DATA (100%)              │\n│                                       │\n│   ┌────────────────┐ ┌──────────┐    │\n│   │  TRAINING 80%  │ │ TEST 20% │    │\n│   │  Model studies │ │ Hidden   │    │\n│   │  these examples│ │ exam     │    │\n│   └────────────────┘ └──────────┘    │\n└──────────────────────────────────────┘\n```\n\n## Why Split?\n\nIt is like a school exam. The teacher does not give the same questions as the homework, otherwise students could just memorize. Test data is the **fair exam**.\n\n## The Process\n\n```\nStep 1: Show 80% to the model\nStep 2: Let it learn\nStep 3: Hide the answers to the other 20%\nStep 4: Ask the model to predict\nStep 5: Compare predictions vs real answers\n```\n\n## Real Example: Loan Approval\n\n```\n10,000 past loan records\n        ↓\n8,000 → train the model\n2,000 → test if it really works\n```\n\n> If a model scores 99% on training but 60% on test, it **memorized** instead of learning. We will fix that on the next page.', 'concept', 4),
('27510ce5-12a7-4eb9-a5b8-2a5ecb864bae', 'Overfitting and Underfitting', E'# Overfitting and Underfitting ⚖️\n\nEvery model lives between two dangers.\n\n## The Two Mistakes\n\n```\n┌──────────────────────────────────────┐\n│       UNDERFITTING (too simple)       │\n│   The model is too lazy.              │\n│   It misses real patterns.            │\n│   Bad on training. Bad on test.       │\n└──────────────────────────────────────┘\n\n┌──────────────────────────────────────┐\n│       OVERFITTING (too obsessed)      │\n│   The model memorized every detail.   │\n│   Even the noise and mistakes.        │\n│   Great on training. Bad on test.     │\n└──────────────────────────────────────┘\n\n┌──────────────────────────────────────┐\n│       JUST RIGHT 🎯                   │\n│   Learns the real signal.             │\n│   Ignores the noise.                  │\n│   Good on training AND test.          │\n└──────────────────────────────────────┘\n```\n\n## Real-Life Analogy\n\n- **Underfitting**: A student who barely studies. Fails every test.\n- **Overfitting**: A student who memorizes the textbook word-for-word. Fails when the exam asks a slightly different question.\n- **Just right**: A student who understands concepts. Can answer new questions.\n\n## How Engineers Fix It\n\n| Problem | Fix |\n|---------|-----|\n| Underfitting | Use a more powerful model, add features |\n| Overfitting | Get more data, simplify the model, use regularization |\n\n> Balancing these two is the **daily job** of every machine learning engineer.', 'concept', 5);

-- Unsupervised Learning (chapter 3206bd83...)
INSERT INTO public.pages (chapter_id, title, content, page_type, order_index) VALUES
('3206bd83-c9c2-46a1-bb8c-b3ace4ed3566', 'Clustering in the Real World', E'# Clustering in the Real World 🎯\n\nClustering groups similar things together — without ever being told what the groups are.\n\n## The Magic\n\n```\n┌──────────────────────────────────────┐\n│         CUSTOMER CLUSTERING           │\n│                                       │\n│   Raw customer data goes in           │\n│            ↓                          │\n│   Algorithm finds 3 natural groups    │\n│                                       │\n│   🟢 Bargain hunters                  │\n│   🔵 Premium buyers                   │\n│   🟡 Occasional shoppers              │\n└──────────────────────────────────────┘\n```\n\n## Where You See It\n\n| Product | Clustering Use |\n|---------|----------------|\n| **Spotify** | Groups songs by mood |\n| **Amazon** | Groups customers for marketing |\n| **Google News** | Groups articles about the same event |\n| **Instagram** | Groups similar accounts to suggest |\n\n## Why It Is Powerful\n\nNo human labeled the groups. The machine **discovered** them on its own. This is great when:\n\n- Labels are expensive to create\n- You do not yet know what groups exist\n- You want to find surprises in the data\n\n> Clustering is how companies turn millions of customers into a few meaningful groups they can actually serve.', 'concept', 2),
('3206bd83-c9c2-46a1-bb8c-b3ace4ed3566', 'Dimensionality Reduction', E'# Dimensionality Reduction 🗜️\n\nReal data often has hundreds of features. Dimensionality reduction shrinks it down — without losing the important parts.\n\n## The Core Idea\n\n```\n┌──────────────────────────────────────┐\n│      BEFORE: 500 features              │\n│      messy, slow, hard to plot         │\n│              ↓                         │\n│      Dimensionality Reduction          │\n│              ↓                         │\n│      AFTER: 2 features                 │\n│      clean, fast, easy to visualize    │\n└──────────────────────────────────────┘\n```\n\n## A Simple Analogy\n\nImagine describing a person with 500 details: height, weight, hobbies, color of every shirt they own…\n\nMost people only need **2 or 3 big traits** (personality, profession, location) to get the picture. Dimensionality reduction does exactly this for data.\n\n## Why It Matters\n\n- Models train **faster**\n- Data becomes **easier to visualize**\n- Removes **noisy** or redundant features\n- Reveals **hidden structure**\n\n## Real Example: Face Recognition\n\n```\nA face photo has millions of pixels.\n        ↓\nReduce to ~128 key numbers.\n        ↓\nThose 128 numbers uniquely identify\nyour face — used by iPhone Face ID.\n```\n\n> Less data, more insight. That is the promise of dimensionality reduction.', 'concept', 3),
('3206bd83-c9c2-46a1-bb8c-b3ace4ed3566', 'Anomaly Detection', E'# Anomaly Detection 🚨\n\nAnomaly detection finds the **odd one out** — events that do not fit the normal pattern.\n\n## How It Works\n\n```\n┌──────────────────────────────────────┐\n│        ANOMALY DETECTION              │\n│                                       │\n│   1. Learn what NORMAL looks like     │\n│   2. Flag anything that does not fit  │\n│                                       │\n│   ✅ ✅ ✅ ✅ ⚠️ ✅ ✅ ✅              │\n│                ↑                      │\n│            Anomaly                    │\n└──────────────────────────────────────┘\n```\n\n## Where It Saves the Day\n\n| Industry | What it catches |\n|----------|-----------------|\n| **Banking** | Fraudulent card swipes |\n| **Healthcare** | Strange heart rhythms |\n| **Manufacturing** | Defective parts on a line |\n| **Cybersecurity** | Hacker login patterns |\n| **Cloud platforms** | Sudden server crashes |\n\n## Why Unsupervised?\n\nWe usually do not have labels for "fraud" or "attack" — they are rare and new types appear every day. So we teach the machine what **normal** looks like, and let it shout when something does not match.\n\n> Visa processes **65,000 transactions per second** with anomaly detection running on every single one.', 'concept', 4);

-- Reinforcement Learning (chapter 76fe2f5d...)
INSERT INTO public.pages (chapter_id, title, content, page_type, order_index) VALUES
('76fe2f5d-132c-4ec3-82fd-65c8f7657eb7', 'Reward Signals in Daily Life', E'# Reward Signals in Daily Life 🍪\n\nReinforcement learning is built on one idea: **good actions get rewards, bad actions get penalties**.\n\n## The Loop\n\n```\n┌──────────────────────────────────────┐\n│       REINFORCEMENT LOOP              │\n│                                       │\n│   AGENT takes an action               │\n│            ↓                          │\n│   ENVIRONMENT responds                │\n│            ↓                          │\n│   REWARD or PENALTY                   │\n│            ↓                          │\n│   AGENT updates its strategy          │\n│            ↻ repeat forever           │\n└──────────────────────────────────────┘\n```\n\n## You Already Live This\n\n| Action | Reward / Penalty |\n|--------|------------------|\n| Eat healthy food | Feel energetic ✅ |\n| Sleep late | Tired the next day ❌ |\n| Help a friend | Stronger friendship ✅ |\n| Touch a hot stove | Pain ❌ |\n\nYour brain is constantly running this loop. So is a reinforcement learning agent.\n\n## Real AI Examples\n\n- **YouTube**: rewards videos that keep you watching\n- **Tesla Autopilot**: rewards smooth, safe driving\n- **AlphaGo**: rewarded for winning Go games\n\n> Reinforcement learning is how AI learns by **doing**, not just by reading.', 'concept', 2),
('76fe2f5d-132c-4ec3-82fd-65c8f7657eb7', 'Exploration vs Exploitation', E'# Exploration vs Exploitation 🗺️\n\nEvery reinforcement learning agent faces the same daily dilemma.\n\n## The Tradeoff\n\n```\n┌──────────────────────────────────────┐\n│       EXPLOITATION                    │\n│   Stick with what you know works.     │\n│   Safe. Predictable. Boring.          │\n└──────────────────────────────────────┘\n\n┌──────────────────────────────────────┐\n│       EXPLORATION                     │\n│   Try something new.                  │\n│   Risky. Sometimes amazing.           │\n│   Sometimes a flop.                   │\n└──────────────────────────────────────┘\n```\n\n## A Human Example\n\nYou go to a restaurant.\n- **Exploit**: order your usual favorite dish.\n- **Explore**: try the new chef''s special.\n\nThe favorite is a guaranteed 8/10. The special could be a 10/10 or a 3/10. Pure exploitation = you never discover better. Pure exploration = you never enjoy what you already know.\n\n## Why AI Cares\n\n- **Netflix** must recommend shows you''ll love (exploit) AND surface new ones to discover your tastes (explore).\n- **Trading bots** balance safe trades vs risky high-reward bets.\n- **Game-playing AI** must try wild strategies to find winning ones.\n\n> The best agents do **both** — exploit most of the time, explore just enough to keep improving.', 'concept', 3);

-- Real ML Products (chapter 8b3ac77c...)
INSERT INTO public.pages (chapter_id, title, content, page_type, order_index) VALUES
('8b3ac77c-dcc2-488e-8886-16faa4922c62', 'How Netflix Recommends', E'# How Netflix Recommends 🎬\n\nNetflix spends **over $1 billion a year** on its recommendation system. Here is the simple version of how it works.\n\n## The Three Signals\n\n```\n┌──────────────────────────────────────┐\n│      NETFLIX RECOMMENDATION ENGINE    │\n│                                       │\n│   1. WHAT YOU WATCHED                 │\n│   2. WHAT SIMILAR USERS WATCHED       │\n│   3. METADATA about each show         │\n│            ↓                          │\n│   Combine all three signals           │\n│            ↓                          │\n│   Personalized homepage for you       │\n└──────────────────────────────────────┘\n```\n\n## A Worked Example\n\n```\nYou watched:\n  • Stranger Things\n  • Dark\n  • Black Mirror\n\nPeople with the same taste also loved:\n  • The OA\n  • Mindhunter\n\nNetflix recommends both, ranked\nby how confident the model is.\n```\n\n## Even the Thumbnails Are AI\n\nNetflix shows you a **different cover image** for the same movie based on what you usually click on. Someone who watches comedies sees the funny scene; someone who watches dramas sees the dramatic one.\n\n## The Business Impact\n\n- **80%** of what people watch on Netflix comes from recommendations\n- Saves the company an estimated **$1 billion per year** in retained subscribers\n\n> This is machine learning paying for itself many times over.', 'example', 2),
('8b3ac77c-dcc2-488e-8886-16faa4922c62', 'Fraud Detection Systems', E'# Fraud Detection Systems 🛡️\n\nEvery time you swipe a card, an ML model decides in **milliseconds** whether to allow or block the transaction.\n\n## The Pipeline\n\n```\n┌──────────────────────────────────────┐\n│       CARD FRAUD DETECTION            │\n│                                       │\n│   Swipe happens                       │\n│            ↓                          │\n│   200+ features collected             │\n│   (amount, location, time, device,    │\n│    merchant, your past habits...)     │\n│            ↓                          │\n│   ML model scores risk 0 → 100        │\n│            ↓                          │\n│   Score < 30 → approve ✅             │\n│   Score 30-70 → ask for OTP 🔐        │\n│   Score > 70 → block ❌               │\n└──────────────────────────────────────┘\n```\n\n## What the Model Looks For\n\n| Signal | Why it matters |\n|--------|----------------|\n| Sudden big purchase | Unusual for you |\n| Country change | You can''t be in 2 places |\n| Unknown device | Possibly stolen card |\n| 3 AM swipe | Outside your habits |\n| Rapid repeat swipes | Bot-like behavior |\n\n## Why ML Wins Here\n\nRule-based systems ("block if > $1000") get fooled easily. ML adapts to **each individual user**: a $50 charge might be normal for you and suspicious for someone else.\n\n## Scale\n\n- **PayPal** scans every transaction in under **5 milliseconds**.\n- **Visa** stopped over **$25 billion** in fraud in 2024.\n\n> Without machine learning, modern digital payments would simply collapse.', 'example', 3);

-- Now add exercises (need page IDs from the inserts we just made)
INSERT INTO public.exercises (page_id, question, exercise_type, options, correct_answer, explanation, xp_reward)
SELECT id, 'In a house price prediction model, what is the "label"?', 'multiple_choice',
  '["The size of the house", "The number of bedrooms", "The actual sale price", "The neighborhood name"]'::jsonb,
  'The actual sale price',
  'Features are the inputs (size, bedrooms, etc.) and the label is the answer the model learns to predict — here, the sale price.', 20
FROM public.pages WHERE chapter_id='32a8dc6a-d56e-44e0-99ce-8fb4dadafafd' AND title='Features vs Labels';

INSERT INTO public.exercises (page_id, question, exercise_type, options, correct_answer, explanation, xp_reward)
SELECT id, 'Which task is a classification problem?', 'multiple_choice',
  '["Predicting tomorrow''s temperature", "Predicting a house price", "Deciding if an email is spam or not", "Predicting a delivery time in minutes"]'::jsonb,
  'Deciding if an email is spam or not',
  'Classification predicts a category (spam / not spam). The other three predict numbers, which is regression.', 20
FROM public.pages WHERE chapter_id='27510ce5-12a7-4eb9-a5b8-2a5ecb864bae' AND title='Regression vs Classification';

INSERT INTO public.exercises (page_id, question, exercise_type, options, correct_answer, explanation, xp_reward)
SELECT id, 'A model scores 99% on training data but only 55% on test data. What is happening?', 'multiple_choice',
  '["Underfitting", "Overfitting", "The model is perfect", "The data is wrong"]'::jsonb,
  'Overfitting',
  'The model memorized the training data instead of learning general patterns, so it fails on new examples. This is overfitting.', 20
FROM public.pages WHERE chapter_id='27510ce5-12a7-4eb9-a5b8-2a5ecb864bae' AND title='Overfitting and Underfitting';

INSERT INTO public.exercises (page_id, question, exercise_type, options, correct_answer, explanation, xp_reward)
SELECT id, 'Why is clustering called "unsupervised" learning?', 'multiple_choice',
  '["It runs without a computer", "Nobody tells the model what the groups should be", "It has no rewards", "It only works on small data"]'::jsonb,
  'Nobody tells the model what the groups should be',
  'In unsupervised learning there are no labels. The algorithm discovers natural groups in the data on its own.', 20
FROM public.pages WHERE chapter_id='3206bd83-c9c2-46a1-bb8c-b3ace4ed3566' AND title='Clustering in the Real World';

INSERT INTO public.exercises (page_id, question, exercise_type, options, correct_answer, explanation, xp_reward)
SELECT id, 'You only ever order your favourite dish at a restaurant. In reinforcement learning terms, you are:', 'multiple_choice',
  '["Exploring", "Exploiting", "Training", "Overfitting"]'::jsonb,
  'Exploiting',
  'Sticking with the known best option is exploitation. Trying something new would be exploration.', 20
FROM public.pages WHERE chapter_id='76fe2f5d-132c-4ec3-82fd-65c8f7657eb7' AND title='Exploration vs Exploitation';

INSERT INTO public.exercises (page_id, question, exercise_type, options, correct_answer, explanation, xp_reward)
SELECT id, 'Roughly what share of Netflix viewing comes from its recommendation system?', 'multiple_choice',
  '["About 20%", "About 50%", "About 80%", "About 5%"]'::jsonb,
  'About 80%',
  'Netflix reports that about 80% of watched content is discovered through recommendations — which is why they invest over $1 billion a year in it.', 20
FROM public.pages WHERE chapter_id='8b3ac77c-dcc2-488e-8886-16faa4922c62' AND title='How Netflix Recommends';

-- Update chapter page counts
UPDATE public.chapters SET total_pages = 6 WHERE id = '32a8dc6a-d56e-44e0-99ce-8fb4dadafafd';
UPDATE public.chapters SET total_pages = 6 WHERE id = '27510ce5-12a7-4eb9-a5b8-2a5ecb864bae';
UPDATE public.chapters SET total_pages = 5 WHERE id = '3206bd83-c9c2-46a1-bb8c-b3ace4ed3566';
UPDATE public.chapters SET total_pages = 4 WHERE id = '76fe2f5d-132c-4ec3-82fd-65c8f7657eb7';
UPDATE public.chapters SET total_pages = 4 WHERE id = '8b3ac77c-dcc2-488e-8886-16faa4922c62';
